// IT Support & Service Desk Email Notification Engine
// Configured recipient for all service tickets: ratanchaurasiya61@gmail.com

export const IT_SUPPORT_EMAIL = 'ratanchaurasiya61@gmail.com';

export interface ServiceTicketEmailPayload {
  ticketId?: string;
  employeeName: string;
  employeeId: string;
  companyEmployeeNumber?: string;
  employeeEmail?: string;
  employeePhone?: string;
  department?: string;
  designation?: string;
  assetNumber: string;
  deviceName: string;
  deviceType?: string;
  manufacturer?: string;
  model?: string;
  serialNumber?: string;
  problemCategory: string;
  urgency: 'Normal' | 'High' | 'Critical';
  issueDescription: string;
  serviceDate: string;
  processor?: string;
  installedRAM?: string;
  storage?: string;
  os?: string;
}

export function generateServiceTicketEmailContent(payload: ServiceTicketEmailPayload) {
  const urgencyUpper = payload.urgency.toUpperCase();
  const ticketId =
    payload.ticketId || `SRV-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`;

  const subject = `[IT SERVICE TICKET - ${urgencyUpper}] ${payload.assetNumber} | ${payload.employeeName} (${payload.problemCategory})`;

  const bodyLines = [
    `=====================================================`,
    `      OFFICIAL IT SERVICE TICKET NOTIFICATION        `,
    `=====================================================`,
    ``,
    `TICKET INFORMATION:`,
    `-----------------------------------------------------`,
    `Ticket ID:          ${ticketId}`,
    `Date Logged:        ${payload.serviceDate}`,
    `Priority / Urgency:  ${urgencyUpper}`,
    `Problem Category:   ${payload.problemCategory}`,
    `Dispatched To:      ${IT_SUPPORT_EMAIL}`,
    ``,
    `EMPLOYEE DETAILS:`,
    `-----------------------------------------------------`,
    `Name:               ${payload.employeeName}`,
    `Employee ID:        ${payload.employeeId}`,
    payload.companyEmployeeNumber ? `Badge / Payroll #:  ${payload.companyEmployeeNumber}` : null,
    payload.department ? `Department:         ${payload.department}` : null,
    payload.designation ? `Designation:        ${payload.designation}` : null,
    payload.employeeEmail ? `Contact Email:      ${payload.employeeEmail}` : null,
    payload.employeePhone ? `Contact Phone:      ${payload.employeePhone}` : null,
    ``,
    `WORKSTATION & ASSET SPECIFICATIONS:`,
    `-----------------------------------------------------`,
    `Asset Tag:          ${payload.assetNumber}`,
    `Device Name:        ${payload.deviceName}`,
    payload.deviceType ? `Device Type:        ${payload.deviceType}` : null,
    payload.manufacturer || payload.model
      ? `Make & Model:       ${payload.manufacturer || ''} ${payload.model || ''}`.trim()
      : null,
    `Serial Number:      ${payload.serialNumber || 'N/A'}`,
    payload.os ? `Operating System:   ${payload.os}` : null,
    payload.processor ? `Processor:          ${payload.processor}` : null,
    payload.installedRAM ? `Installed RAM:      ${payload.installedRAM}` : null,
    payload.storage ? `Storage Capacity:   ${payload.storage}` : null,
    ``,
    `ISSUE DESCRIPTION & OBSERVED SYMPTOMS:`,
    `-----------------------------------------------------`,
    payload.issueDescription,
    ``,
    `-----------------------------------------------------`,
    `Initial Status:     In Progress (Assigned for IT Diagnostics)`,
    `Generated by:       AssetCore Enterprise Fleet Management`,
    `Notification Target: ${IT_SUPPORT_EMAIL}`,
    `=====================================================`,
  ].filter(line => line !== null);

  const body = bodyLines.join('\n');

  return {
    to: IT_SUPPORT_EMAIL,
    subject,
    body,
    ticketId,
  };
}

/**
 * Sends service ticket directly via background API to ratanchaurasiya61@gmail.com
 */
export async function sendEmailViaApi(payload: ServiceTicketEmailPayload): Promise<boolean> {
  try {
    const { subject, body, ticketId } = generateServiceTicketEmailContent(payload);
    const response = await fetch(`https://formsubmit.co/ajax/${IT_SUPPORT_EMAIL}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({
        _subject: subject,
        ticketId,
        urgency: payload.urgency,
        category: payload.problemCategory,
        employee: `${payload.employeeName} (${payload.employeeId})`,
        workstation: `${payload.assetNumber} - ${payload.deviceName}`,
        serialNumber: payload.serialNumber || 'N/A',
        description: payload.issueDescription,
        serviceTicketBody: body,
      }),
    });
    const data = await response.json();
    return !!data.success;
  } catch (err) {
    console.warn('Direct API email dispatch attempt:', err);
    return false;
  }
}

/**
 * Automatically prepares and dispatches the service ticket details to ratanchaurasiya61@gmail.com
 * Opens Gmail Web compose directly, triggers native mailto, and attempts background API dispatch.
 */
export function dispatchServiceTicketEmail(payload: ServiceTicketEmailPayload, openDirectly = true): {
  success: boolean;
  mailtoUrl: string;
  gmailComposeUrl: string;
  ticketId: string;
  subject: string;
  body: string;
} {
  const { to, subject, body, ticketId } = generateServiceTicketEmailContent(payload);

  const encodedSubject = encodeURIComponent(subject);
  const encodedBody = encodeURIComponent(body);

  const mailtoUrl = `mailto:${to}?subject=${encodedSubject}&body=${encodedBody}`;
  const gmailComposeUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${to}&su=${encodedSubject}&body=${encodedBody}`;

  // 1. Open Gmail Web compose in a new tab directly if openDirectly is true
  if (openDirectly && typeof window !== 'undefined') {
    try {
      const openedWindow = window.open(gmailComposeUrl, '_blank');
      if (!openedWindow) {
        console.warn('Popup window blocked by browser; user can use on-screen button.');
      }
    } catch (e) {
      console.warn('Could not auto-open Gmail compose window:', e);
    }
  }

  // 2. Trigger mailto backup using hidden anchor
  try {
    const link = document.createElement('a');
    link.href = mailtoUrl;
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      try {
        document.body.removeChild(link);
      } catch {}
    }, 600);
  } catch (err) {
    console.warn('Mailto anchor dispatch error:', err);
  }

  // 3. Attempt direct background API dispatch to ratanchaurasiya61@gmail.com
  sendEmailViaApi(payload).catch(() => {});

  return {
    success: true,
    mailtoUrl,
    gmailComposeUrl,
    ticketId,
    subject,
    body,
  };
}

// -------------------------------------------------------------
// MULTI-ASSET REQUISITION EMAIL ENGINE
// Dispatches structured employee equipment requests to ratanchaurasiya61@gmail.com
// -------------------------------------------------------------

export interface AssetRequestEmailPayload {
  requestId?: string;
  employeeName: string;
  employeeId: string;
  companyEmployeeNumber?: string;
  employeeEmail?: string;
  employeePhone?: string;
  department?: string;
  designation?: string;
  requestDate: string;
  urgency: 'Normal' | 'High' | 'Critical';
  items: Array<{
    assetType: string;
    customAssetName?: string;
    quantity: number;
    specifications?: string;
  }>;
  reason: string;
}

export function generateAssetRequestEmailContent(payload: AssetRequestEmailPayload) {
  const urgencyUpper = payload.urgency.toUpperCase();
  const requestId =
    payload.requestId || `REQ-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`;

  const totalItemsCount = payload.items.length;
  const totalUnits = payload.items.reduce((sum, item) => sum + (item.quantity || 1), 0);

  const subject = `[EQUIPMENT REQUEST - ${urgencyUpper}] ${payload.employeeName} (${payload.employeeId}) - ${totalUnits} Assets Requested`;

  const itemLines: string[] = [];
  payload.items.forEach((item, idx) => {
    const itemName = item.customAssetName ? `${item.assetType} (${item.customAssetName})` : item.assetType;
    const spec = item.specifications ? ` [Notes: ${item.specifications}]` : '';
    itemLines.push(`  ${idx + 1}. ${itemName} — Qty: ${item.quantity} unit(s)${spec}`);
  });

  const bodyLines = [
    `=====================================================`,
    `       OFFICIAL EMPLOYEE EQUIPMENT REQUISITION        `,
    `=====================================================`,
    ``,
    `REQUISITION DETAILS:`,
    `-----------------------------------------------------`,
    `Request ID:         ${requestId}`,
    `Date Submitted:     ${payload.requestDate}`,
    `Priority / Urgency: ${urgencyUpper}`,
    `Status:             Pending Admin Review & Allocation`,
    `Dispatched To:      ${IT_SUPPORT_EMAIL}`,
    ``,
    `EMPLOYEE DETAILS:`,
    `-----------------------------------------------------`,
    `Name:               ${payload.employeeName}`,
    `Employee ID:        ${payload.employeeId}`,
    payload.companyEmployeeNumber ? `Badge / Payroll #:  ${payload.companyEmployeeNumber}` : null,
    payload.department ? `Department:         ${payload.department}` : null,
    payload.designation ? `Designation:        ${payload.designation}` : null,
    payload.employeeEmail ? `Contact Email:      ${payload.employeeEmail}` : null,
    payload.employeePhone ? `Contact Phone:      ${payload.employeePhone}` : null,
    ``,
    `REQUESTED ASSETS & EQUIPMENT (${totalItemsCount} Types, ${totalUnits} Total Units):`,
    `-----------------------------------------------------`,
    ...itemLines,
    ``,
    `BUSINESS JUSTIFICATION & PURPOSE:`,
    `-----------------------------------------------------`,
    payload.reason,
    ``,
    `-----------------------------------------------------`,
    `Generated by:       AssetCore Enterprise Fleet Management`,
    `Notification Target: ${IT_SUPPORT_EMAIL}`,
    `Admin Action:       Review, Approve & Allocate from Inventory`,
    `=====================================================`,
  ].filter(line => line !== null);

  const body = bodyLines.join('\n');

  return {
    to: IT_SUPPORT_EMAIL,
    subject,
    body,
    requestId,
  };
}

export function dispatchAssetRequestEmail(payload: AssetRequestEmailPayload, openDirectly: boolean = false) {
  const { to, subject, body, requestId } = generateAssetRequestEmailContent(payload);

  const encodedSubject = encodeURIComponent(subject);
  const encodedBody = encodeURIComponent(body);

  const mailtoUrl = `mailto:${to}?subject=${encodedSubject}&body=${encodedBody}`;
  const gmailComposeUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${to}&su=${encodedSubject}&body=${encodedBody}`;

  if (openDirectly && typeof window !== 'undefined') {
    try {
      const openedWindow = window.open(gmailComposeUrl, '_blank');
      if (!openedWindow) {
        console.warn('Popup blocked; use action button.');
      }
    } catch (e) {
      console.warn('Could not auto-open Gmail compose window:', e);
    }
  }

  if (openDirectly && typeof document !== 'undefined') {
    try {
      const link = document.createElement('a');
      link.href = mailtoUrl;
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      setTimeout(() => {
        try {
          document.body.removeChild(link);
        } catch {}
      }, 600);
    } catch (err) {
      console.warn('Mailto anchor dispatch error:', err);
    }
  }

  return {
    success: true,
    mailtoUrl,
    gmailComposeUrl,
    requestId,
    subject,
    body,
  };
}
